/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package churchsystem;

import static churchsystem.HomePage.username2;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author UMAGAGEE
 */
public class ChangPassword extends javax.swing.JFrame {
         Connection con=null;
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String username;

    /**
     * Creates new form ChangPassword
     */
    public ChangPassword() {
        initComponents();
            setLocationRelativeTo(null);
         con=ConnectionToDatabase.conn();
       //  con=creatConnection.conn();
         lblMatch1.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblMatch1 = new javax.swing.JLabel();
        oldPass = new javax.swing.JPasswordField();
        Cpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 340, 50));

        lblMatch1.setBackground(new java.awt.Color(255, 255, 255));
        lblMatch1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMatch1.setForeground(java.awt.Color.red);
        lblMatch1.setText("* Password do not match");
        lblMatch1.setOpaque(true);
        jPanel1.add(lblMatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 260, -1));

        oldPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(oldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 320, 40));

        Cpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpassActionPerformed(evt);
            }
        });
        Cpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CpassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CpassKeyTyped(evt);
            }
        });
        jPanel1.add(Cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 320, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("New Password");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Old Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        newPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 320, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(51, 204, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setText("HOME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        jLabel23.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 0, 0));
        jLabel23.setText("CHANGE PASSWORD");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 390, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Opass=oldPass.getText();
        String  Npass=newPass.getText().trim();
        String   cPass=Cpass.getText();

        //Hashing Password
        //PasswordHashing hp=new PasswordHashing();
        //String hashedPassword=hp.hashPassword(Npass, Npass);
        //String hashedPassword1=hp.hashPassword(Opass, Opass);
        //

        if( Opass.equals("") || Npass.equals("") || cPass.equals("")){
            JOptionPane.showMessageDialog(null, "One or More field is empty");

        }

        else{

            try{

                if(!Npass.equals(cPass)){
                    lblMatch1.show();
                }else{
                    ps=con.prepareStatement("Select Password from registration WHERE  id='"+username2.getText()+"' ");
                    rs=ps.executeQuery();
                    if(rs.next()){

                        String dbPass=rs.getString("password");
                        if(Opass.equals(dbPass)){

                            String sql="update registration set Password=? WHERE  id='"+username2.getText()+"' ";
                            ps=con.prepareStatement(sql);
                            ps.setString(1, Npass);
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Your password has Successfully been Change");
                            oldPass.setText("");
                            newPass.setText("");
                            Cpass.setText("");
                        }else{
                            JOptionPane.showMessageDialog(null, "Wrong Credentials 2 ");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Wrong Credentials 2 ");
                    }

                }

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpassActionPerformed

    }//GEN-LAST:event_CpassActionPerformed

    private void CpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpassKeyReleased
        Font f = new Font("serif", Font.PLAIN,25);
        Graphics g;
        lblMatch1.show();
        String pass = newPass.getText().trim();
        String cpass = Cpass.getText().trim();
        try{
            if(pass.equals(cpass)){
                lblMatch1.setForeground(Color.decode("#009900"));
                lblMatch1.setText("Password Match");
                jButton1.setEnabled(true);
            }else{
                lblMatch1.setText("* Please Password Match");
                jButton1.setEnabled(false);
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CpassKeyReleased

    private void CpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CpassKeyTyped

    }//GEN-LAST:event_CpassKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        HomePage h=new HomePage();

        this.setVisible(false);
        h.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMatch1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPasswordField oldPass;
    // End of variables declaration//GEN-END:variables
}
