/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package churchsystem;

import churchsystem.ConnectionToDatabase;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author UMAGAGEE
 */
public class ChurchInfo extends javax.swing.JFrame {
Connection con = null;
PreparedStatement ps= null;
ResultSet rs = null;
Statement stm=null;
    String imagePath=null;
    /**
     * Creates new form SchoolInfo
     */
    public ChurchInfo() {
        initComponents();
        setLocationRelativeTo(null);
        jLabelId.hide();
       con=ConnectionToDatabase.conn();
        schoolInfo();
    }
      int pos=0;
    
    //Function to Resize Image to fit into Jlabel 
    public ImageIcon ResizeImage(String imagePath,byte[] pic){
    ImageIcon myImage = null;
     if(imagePath!=null){
      myImage=new ImageIcon(imagePath);
     }
     else{
     myImage=new ImageIcon(pic);
     }
     
     Image img1 = myImage.getImage();
     Image img2 = img1.getScaledInstance(lblPicture.getWidth(),lblPicture.getHeight(),Image.SCALE_SMOOTH);
     ImageIcon image =new ImageIcon(img2);
     return image;
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblPicture = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        txtSchoolName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        txtTelephone2 = new javax.swing.JTextField();
        txtTelephone1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(102, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(102, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Logo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel11.setBackground(new java.awt.Color(153, 153, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPicture.setBackground(new java.awt.Color(255, 255, 255));
        lblPicture.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 180, 210));

        jPanel12.setBackground(new java.awt.Color(102, 204, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("UPDATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("BROWSE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 250));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Telephone Number2:");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("School Name:");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabelId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID");
        jPanel10.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        txtSchoolName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSchoolName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSchoolNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSchoolNameKeyTyped(evt);
            }
        });
        jPanel10.add(txtSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 560, 30));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddressKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtAddress);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 310, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Telephone Number1:");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtTelephone2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel10.add(txtTelephone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, 30));

        txtTelephone1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel10.add(txtTelephone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Address:");
        jPanel10.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 21, 890, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("SCHOOL INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 218, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 218, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 365, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 70, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Save This  SChool Information?","Save Record",JOptionPane.YES_NO_OPTION);
if(p==0){
        if(checkInputs() && imagePath !=null){
                try{

ps=con.prepareStatement("INSERT INTO school_info (Name,Address,Number1,Number2,logo)"
                    + " values(?,?,?,?,?)");

                ps.setString(1, txtSchoolName.getText().trim());
                ps.setString(2, txtAddress.getText().trim());
                ps.setString(3, txtTelephone1.getText().trim());
                ps.setString(4, txtTelephone2.getText().trim());
                InputStream img;
                img = new FileInputStream(new File(imagePath));
                ps.setBlob(5,img);
                
                ps.execute();
                schoolInfo();
               
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
            }
            catch(HeadlessException | FileNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null,e.getMessage());

            }
            finally {
                try{
                   
                    con.close();
                }
                catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "One or more field is empty");
        
        }

}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                     ///Selecting images
        try{
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));

            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png");

            file.addChoosableFileFilter(filter);
            int result =file.showSaveDialog(null);
            if(result==JFileChooser.APPROVE_OPTION){
                File selectedFile=file.getSelectedFile();
                String path=selectedFile.getAbsolutePath();
                lblPicture.setIcon(ResizeImage(path,null));
                imagePath=path;
            }
            else{
                JOptionPane.showMessageDialog(null, "No file");
            }
        }
        catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Error!");

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtSchoolNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSchoolNameKeyReleased
   
    }//GEN-LAST:event_txtSchoolNameKeyReleased

    private void txtSchoolNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSchoolNameKeyTyped
    char keyChar = evt.getKeyChar();
    if(Character.isLowerCase(keyChar)){
        evt.setKeyChar(Character.toUpperCase(keyChar));
    }
    }//GEN-LAST:event_txtSchoolNameKeyTyped

    private void txtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyTyped
         char keyChar = evt.getKeyChar();
    if(Character.isLowerCase(keyChar)){
        evt.setKeyChar(Character.toUpperCase(keyChar));
    }
    }//GEN-LAST:event_txtAddressKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
              int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            if(checkInputs() && imagePath !=null){

                try{

String sql= "update school_info set Name=?,Address=?,Number1=?,Number2=?,logo=?"
        + "where id='"+jLabelId.getText()+"'";

                ps=con.prepareStatement(sql);
                ps.setString(1, txtSchoolName.getText());
                ps.setString(2, txtAddress.getText());
                ps.setString(3, txtTelephone1.getText());
                ps.setString(4,txtTelephone2.getText());
                InputStream img;
                img = new FileInputStream(new File(imagePath));
                ps.setBlob(5,img);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated");
               schoolInfo();
                    

                }catch(HeadlessException | FileNotFoundException | SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                //Updating without Image
            }else if(checkInputs() && imagePath ==null){

                try{

String sql= "update school_info set Name=?,Address=?,Number1=?,Number2=?"
        + "where id='"+jLabelId.getText()+"'";

                ps=con.prepareStatement(sql);
                ps.setString(1, txtSchoolName.getText());
                ps.setString(2, txtAddress.getText());
                ps.setString(3, txtTelephone1.getText());
                ps.setString(4,txtTelephone2.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated");
               schoolInfo();
                    

                }catch(HeadlessException  | SQLException e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChurchInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChurchInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChurchInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChurchInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChurchInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtSchoolName;
    private javax.swing.JTextField txtTelephone1;
    private javax.swing.JTextField txtTelephone2;
    // End of variables declaration//GEN-END:variables
boolean checkInputs(){
       if(txtSchoolName.getText()==null || txtAddress.getText()==null || txtTelephone1.getText()==null 
               || txtTelephone2.getText()==null ){
           return false;
       }else{
           try{
               Integer.parseInt(txtTelephone1.getText());
               Integer.parseInt(txtTelephone2.getText());
               return true;
           }catch(NumberFormatException e ){
             JOptionPane.showMessageDialog(null,e.getMessage());
             return false;
           }
       
       }
    
}
 void schoolInfo(){
      try{
        
        
        String sql ="select * from school_info";
        
        ps=con.prepareStatement(sql);
        rs=ps.executeQuery();
        if(rs.next()){
            
                 String id = rs.getString("id");
                jLabelId.setText(id);
            
                 String name = rs.getString("Name");
                txtSchoolName.setText(name);

                 String adress = rs.getString("Address");
                txtAddress.setText(adress);
                
                String num1 = rs.getString("Number1");
                txtTelephone1.setText('0'+num1);

                String num2 = rs.getString("Number2");
                txtTelephone2.setText('0'+num2);

                 byte[]pic=rs.getBytes("logo");
                
                if(pic == null){
                    
                }else{
                ImageIcon image=new ImageIcon(pic);
                Image im= image.getImage();
                Image myimg=im.getScaledInstance(lblPicture.getWidth(), lblPicture.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage=new ImageIcon(myimg);
                lblPicture.setIcon(newImage);
                }
        
        }

    }
    catch(SQLException e){
    JOptionPane.showMessageDialog(null, e);
    }
 
 }
}
