/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package churchsystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Steve
 */
public class Registration extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
      conn=ConnectionToDatabase.conn();
        setLocationRelativeTo(null);
        jLabel13.hide();
        jButton2.setEnabled(false);
         jButton4.setEnabled(false);
         jLabel1.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfn = new javax.swing.JTextField();
        txtSn = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Repeat Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, 30));

        txtfn.setBackground(new java.awt.Color(102, 102, 102));
        txtfn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtfn.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, 30));

        txtSn.setBackground(new java.awt.Color(102, 102, 102));
        txtSn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtSn.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtSn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 240, 30));

        txtContact.setBackground(new java.awt.Color(102, 102, 102));
        txtContact.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(255, 255, 255));
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactKeyPressed(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 240, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Admin", "Assistant" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 240, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Contact");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Date of Birth");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("SurName");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("FirstName");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 240, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setPreferredSize(new java.awt.Dimension(89, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.setPreferredSize(new java.awt.Dimension(89, 50));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setPreferredSize(new java.awt.Dimension(89, 50));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Reset");
        jButton5.setPreferredSize(new java.awt.Dimension(89, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 420, 70));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 240, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Username");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("FirstName");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("ID");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(102, 102, 102));
        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 240, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Repeat Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, 30));

        txtUser.setBackground(new java.awt.Color(102, 102, 102));
        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 240, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Search");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, 30));

        txtsearch.setBackground(new java.awt.Color(102, 102, 102));
        txtsearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 30));

        jButton7.setBackground(new java.awt.Color(51, 204, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton7.setText("HOME");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel24.setFont(new java.awt.Font("Andalus", 1, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 0, 0));
        jLabel24.setText("REGISTRATION");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 680, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?", "Add Record", JOptionPane.YES_NO_OPTION);
            if (p == 0) {
                if(txtfn.getText().equals("") || txtSn.getText().equals("")
                    || jDateChooser1.getDate()==null || txtContact.getText().equals("")
                     || txtUser.getText().equals("")|| jPasswordField1.getText().equals("")
                    || jComboBox1.getSelectedIndex()==0   ){
                    JOptionPane.showMessageDialog(null, "Complete  Information", "Missing Information", 2);
                }
                else{

                try {
                    String sql = "insert into registration "
                            + "(Firstname,Surname,Date_O_B,contact,username,password,Status) values (?,?,?,?,?,?,?) ";

                    pst = conn.prepareStatement(sql);
                    
                    pst.setString(1, txtfn.getText().trim());
                    pst.setString(2, txtSn.getText().trim());
                    
                    SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                    String dob=dateFormat.format(jDateChooser1.getDate());
                    pst.setString(3,dob);
                    
                    pst.setString(4, txtContact.getText().trim());
                    pst.setString(5, txtUser.getText().trim().toLowerCase());
                    pst.setString(6, jPasswordField1.getText().trim());
                    pst.setString(7, jComboBox1.getSelectedItem().toString().trim());
                    
                    pst.execute();
                    clear();
                    JOptionPane.showMessageDialog(null, "Data is saved successfully");
                   
                } catch (HeadlessException | SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
  
              }
                        }
                
                }
                      
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);    }//GEN-LAST:event_formWindowClosing

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int p = JOptionPane.showConfirmDialog(null, ", Are you sure you want to UPDATE this Person? Confirm and Proceed ","",JOptionPane.YES_NO_OPTION);
        if(p==0){          
        if(txtfn.getText().equals("") || txtSn.getText().equals("")
                    || jDateChooser1.getDate()==null || txtContact.getText().equals("")
                     || txtUser.getText().equals("")|| jPasswordField1.getText().equals("")
                    || jComboBox1.getSelectedIndex()==0)    {
            JOptionPane.showMessageDialog(null, "Complete Drug Information", "Missing Information", 2);
        } else {

            try {
  String sql= "update registration set Firstname=?,Surname=?,Date_O_B=?,contact=?,Status=?,username=? where id='"+jLabel13.getText().trim()+"' ";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txtfn.getText().trim());
                pst.setString(2, txtSn.getText().trim());
                SimpleDateFormat dateFormat=new SimpleDateFormat("yyy-MM-dd");
                String dob=dateFormat.format(jDateChooser1.getDate());
                pst.setString(3,dob);
                pst.setString(4, txtContact.getText().trim());
                pst.setString(5, jComboBox1.getSelectedItem().toString());
                pst.setString(6, txtUser.getText().trim());
                           pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Person has been Updated Successfully", "Success Operation", 1);
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
                clear();
            }
            
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "You can't Change it, Are you sure you want to DELETE this Person? Confirm and Proceed ","",JOptionPane.YES_NO_OPTION);
        if(p==0){         
                String sql = "delete from registration where id='" + jLabel13.getText().trim() + "' ";
                    try {
                        pst = conn.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Person has been deleted Successfully", "Success Operation", 1);
                        clear();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage(), "Error", 2);
                        clear();
                    }
        }
              
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       clear();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
            jPasswordField1.setEditable(false);
            jPasswordField2.setEditable(false);
            jButton2.setEnabled(true);
            jButton4.setEnabled(true);
      String st=txtsearch.getText().trim();
      if(st.equals("")){
           clear();
       }else{
String sql="Select * from registration where username like '"+st+"%' OR Firstname like '"+st+"%' OR Surname like '"+st+"%' OR contact like '"+st+"%' ";

    try {
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        if(rs.next()){
             String id = rs.getString("id");
        jLabel13.setText(id);
          jLabel13.show();
          
          String fn = rs.getString("Firstname");
        txtfn.setText(fn);
        
        String user = rs.getString("username");
        txtUser.setText(user);
        
        String sn = rs.getString("Surname");
        txtSn.setText(sn);
        
       Date dob = rs.getDate("Date_O_B");
         jDateChooser1.setDate(dob);
        
        String contact = rs.getString("contact");
         txtContact.setText(contact);
         
         String pass = rs.getString("password");
         jPasswordField1.setText(pass);
         
          String held = rs.getString("status");
        jComboBox1.setSelectedItem(held);
        
                     

        } else{
          JOptionPane.showMessageDialog(null, "No Record Found");
          clear();
        } 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage());
        
    }
    } 
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyPressed
              //Preventing user from entering a String  
        String number =txtContact.getText().trim();
        int l=number.length();
        if((evt.getKeyChar() >= '0' && evt.getKeyChar()<='9' || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE ||
                evt.getKeyChar()==KeyEvent.VK_RIGHT || evt.getKeyChar()==KeyEvent.VK_LEFT)){
            txtContact.setEditable(true);
        }else{
            txtContact.setEditable(false);
          // txtContact.setText("");
             JOptionPane.showMessageDialog(null, "*Please Enter only digits(0-9)");
        }
    }//GEN-LAST:event_txtContactKeyPressed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
    Font f = new Font("serif", Font.PLAIN,25);
    Graphics g;
        jLabel1.show();
      String pass = jPasswordField1.getText().trim();
      String cpass = jPasswordField2.getText().trim();
        try{
            if(pass.equals(cpass)){
                jLabel1.setForeground(Color.decode("#009900"));
                jLabel1.setText("Password Match");
                jButton1.setEnabled(true);
            }else{
             jLabel1.setText("* Please Password Match");
                jButton1.setEnabled(false);
            }
          
      }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
   
    }//GEN-LAST:event_txtsearchKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        HomePage h=new HomePage();
        h.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtSn;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtfn;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

void clear(){
 txtfn.setText("");
 txtUser.setText("");
txtSn.setText("");
jDateChooser1.setDate(null);
txtsearch.setText("");
jPasswordField1.setText("");
jPasswordField2.setText("");
jComboBox1.setSelectedIndex(0);
txtContact.setText("");
 jPasswordField1.setEditable(true);
 jLabel13.hide();
 jButton2.setEnabled(false);
 jButton4.setEnabled(false);
}
}
